#!/bin/bash

#check if script was run as root and exit if true
if [ $UID -ne 0 ]
then
  echo "Please run this script with sudo."
  exit
fi

#Define variables
output=$HOME/Research/sys_info.txt
ip=$(ip addr | grep inet | tail -2 | head -1)
suids=$(sudo find / -type f -perm /4000 2>  /dev/null)
cpu=$(lscpu | grep CPU)
disk=$(df -H | head -2)

#Define List to use later
commands=(
  'date'
  'uname -a'
  'hostname -s'
)

files=(
  '/etc/passwd'
  '/etc/shadow'
  '/etc/hosts'
)

#Check for Research directory. Create it if needed.
#if [ ! -d $HOME/Research]
#then
# mkdir $HOME/Research
#fi

#check for output file create if needed
#if [ -f $output ]
#then
#  > $output
#fi

#####################################################################
#Start Script

#Introduction of Information
echo "A Quick System Audit Script" >>  $output
echo "" >> $output

for x in {0..2} ;
do
  results=$(${commands[$x]})
  echo "Results of "${commands[$x]}" command:" >> $output
  echo $results >> $output
  echo "" >> $output
done

#Display Machine Type
echo "Machine Type Info:" >> $output
echo -e "$MACHTYPE \n" >> $output

#Display IP Address Information
echo -e "IP info:" >> $output
echo -e "$ip \n" >> $output

#Display Memory Usage
echo "\nMemory Info:" >> $output
free -h >> $output

#Display CPU Usage
echo -e "\nCPU Info:" >> $output
lscpu |grep CPU >> $output

#Display Disk Usage
echo -e "\nDisk Usage:" >> $output
df -H | head -2 >> $output

#Display who is logged in
echo -e "\nWho is logged in: \n $(who -a) \n" >> $output
echo -e "\nSUID Files:" >> $output

#Display DNS Info
echo "DNS Servers: " >> $output
cat /etc/resolv.conf >> $output

#List SUID Files
echo -e "\nSUID Files:" >> $output
for suid in $suids;
do
  echo $suid >> $output
done

#List of top 10 processes
echo -e "\nTop 10 Processes" >> $output
ps aux --sort -%mem | awk {'print $1, $2, $3, $4, $11'} | head >> $output

#Check the permission on files 

echo -e "\nThe Permissions for sensitive /etc files: \n" >> $output
for file in ${files[@]};
do
  ls -l $file >> $output
done

#Check sudo ability of each user that has a home
for user in $(ls /home)
  do
  sudo -lU $user
done

# Missing info
echo -e "Uname info: $(uname -a) \n" >> $output
echo -e "Hostname: $(hostname -s) " >> $output
echo $execs >> $output
sudo find /home -type f -perm 777 >> $output
